-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 18:49:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`budgets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`budgets` (
  `bdt_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`bdt_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`room_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_types` (
  `rtp_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`rtp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`styles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`styles` (
  `stl_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`stl_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`leads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leads` (
  `lds_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL DEFAULT '',
  `time_data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `phone_number` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  `comment` TEXT NULL DEFAULT NULL,
  `budgets_bdt_id` INT NOT NULL,
  `styles_stl_id` INT NOT NULL,
  `room_types_rtp_id` INT NOT NULL,
  `area` INT NOT NULL,
  `consent_accepted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Согласие на обработку данных',
  PRIMARY KEY (`lds_id`),
  INDEX `fk_leads_budgets_idx` (`budgets_bdt_id` ASC) VISIBLE,
  INDEX `fk_leads_styles1_idx` (`styles_stl_id` ASC) VISIBLE,
  INDEX `fk_leads_room_types1_idx` (`room_types_rtp_id` ASC) VISIBLE,
  CONSTRAINT `fk_leads_budgets`
    FOREIGN KEY (`budgets_bdt_id`)
    REFERENCES `mydb`.`budgets` (`bdt_id`),
  CONSTRAINT `fk_leads_room_types1`
    FOREIGN KEY (`room_types_rtp_id`)
    REFERENCES `mydb`.`room_types` (`rtp_id`),
  CONSTRAINT `fk_leads_styles1`
    FOREIGN KEY (`styles_stl_id`)
    REFERENCES `mydb`.`styles` (`stl_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`zones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zones` (
  `zns_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`zns_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`leads_has_zones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leads_has_zones` (
  `leads_lds_id` INT NOT NULL,
  `zones_zns_id` INT NOT NULL,
  PRIMARY KEY (`leads_lds_id`, `zones_zns_id`),
  INDEX `fk_leads_has_zones_zones1_idx` (`zones_zns_id` ASC) VISIBLE,
  INDEX `fk_leads_has_zones_leads1_idx` (`leads_lds_id` ASC) VISIBLE,
  CONSTRAINT `fk_leads_has_zones_leads1`
    FOREIGN KEY (`leads_lds_id`)
    REFERENCES `mydb`.`leads` (`lds_id`),
  CONSTRAINT `fk_leads_has_zones_zones1`
    FOREIGN KEY (`zones_zns_id`)
    REFERENCES `mydb`.`zones` (`zns_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `mydb` ;

-- -----------------------------------------------------
-- procedure sp_create_lead
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_create_lead`(
    IN p_phone VARCHAR(20),
    IN p_first_name VARCHAR(100),
    IN p_area INT,
    IN p_room_type_id INT,
    IN p_budget_id INT,
    IN p_style_id INT,
    IN p_email VARCHAR(255)
)
BEGIN
    -- Вставляем только то, что осталось (без last_name и status)
    INSERT INTO `leads` (
        `phone_number`,
        `first_name`,
        `area`,
        `room_types_rtp_id`,
        `budgets_bdt_id`,
        `styles_stl_id`,
        `email`,
        `consent_accepted`
    ) VALUES (
        p_phone,
        p_first_name,
        p_area,
        p_room_type_id,
        p_budget_id,
        p_style_id,
        IFNULL(p_email, ''),
        1
    );

    SELECT LAST_INSERT_ID() AS new_id;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
